server:
  port: ${server_port:8080}

lotus:
  apiGateway: ${lotus_api_gateway:http://192.168.77.252:1234/rpc/v0}
  authorization: ${lotus_authorization:}
  cron: ${spider_cron:0 0/1 * * * ?}

spider:
  threadNum: ${spider_thread_num:5}
  downloadTimeout: ${spider_download_timeout:10000}
  cron: ${spider_cron:0 0/1 * * * ?}
